### ISSUE TITLE
Segfaults when opening non-existent file

### ISSUE THREAD

**Issue by kurpitsa** [benkasminbullock/Image-PNG#15]
```
>cat test.pl

use Image::PNG;
my $png = Image::PNG->new();
$png->read("abcdef");

>perl test.pl
zsh: segmentation fault  perl test.pl
```

I think it should check if the file exists prior to trying to open it.

**Comment by benkasminbullock** [comment]
I've confirmed this bug and traced it back to not checking the return value of "open" in tmpl/Container.pm.tmpl. It should be fixed by commit dff4678b1deaa602af5b7a155989cead1afbe026.

I'm going to look over the module and see if there is any other easy thing to fix then release a new version to CPAN later.

**Comment by benkasminbullock** [comment]
I've released a new version to CPAN. If you have time, could you install it and test it works for you.

https://metacpan.org/release/Image-PNG

If I don't hear from you I'll assume it's OK.

**Comment by kurpitsa** [comment]
Thank you! I I did not find any problems with this new release based on the unit tests of my code base.

**Comment by benkasminbullock** [comment]
Thanks. I had no idea anyone was using Image::PNG. Most of the development effort went to Image::PNG::Libpng, and some of the functions planned for Image::PNG ended up in that module instead.

Thanks for your bug report, and please let me know if you have any further issues with this module.
